services:
    _defaults:
        public: true

    AuthBundle\Service\:
        resource: '../../../AuthBundle/Service/*'

    auth.form.register:
        class: AuthBundle\Form\RegisterForm
        autowire: true
        tags: [form.type]