services:
    auth.captcha_service:
        class: AuthBundle\Service\Captcha\Captcha

    auth.service:
        class: AuthBundle\Service\AuthService
        arguments: ['@em', '@security.password_encoder']