parameters:
    entity_repositories:
        SecureBundle\Entity\UserOrder: SecureBundle\Repository\UserOrderRepository
        SecureBundle\Entity\StatusOrder: SecureBundle\Repository\StatusOrderRepository
