auth_bundle_routings:
    resource: "@AuthBundle/Resources/config/routing.yml"
    prefix: /

secure_bundle_routings:
    resource: "@SecureBundle/Resources/config/routing.yml"
    prefix: /

admin_bundle_routings:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

oneup_uploader:
    resource: .
    type: uploader