security:
    encoders:
        SecureBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_MANAGER, ROLE_DIRECTOR]
        ROLE_DIRECTOR: ROLE_MANAGER

    providers:
        database_users:
            entity: { class: SecureBundle:User, property: email }
#        in_memory:
#            memory:
#                users:
#                    user:
#                        password: 123456
#                        roles: 'ROLE_USER'
#                    admin:
#                        password: 123456
#                        roles: 'ROLE_ADMIN'
#                    ryan:
#                        password: $2a$12$LCY0MefVIEc3TYPHV9SNnuzOfyr2p/AXIGoQJEDs4am4JwhNz/jli
#                        roles: 'ROLE_USER'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern: ^/
            anonymous: true
            form_login:
                check_path: login
                login_path: login
                default_target_path: secure_index
                use_referer: true
                #failure_path: login_failure
                #always_use_default_target_path: true
                csrf_token_generator: security.csrf.token_manager

            logout:
                path: /logout
                target: login
                handlers: ['SecureBundle\Service\Listener\LogoutListener']

    access_control:
        - { path: ^/secure/index, roles: [ROLE_ADMIN, ROLE_MANAGER, ROLE_DIRECTOR, ROLE_USER] }
        - { path: ^/secure/admin, roles: ROLE_ADMIN }
        - { path: ^/secure/manager, roles: ROLE_MANAGER }
        - { path: ^/secure/director, roles: ROLE_DIRECTOR }
        - { path: ^/secure/user, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }