services:
    _defaults:
        public: true
        bind:
            $activityLogger: '@SecureBundle\Service\UserActivityService'
            $em: '@doctrine.orm.entity_manager'
            $eventDispatcher: '@event_dispatcher'

    SecureBundle\Service\Listener\:
        resource: '../../../SecureBundle/Service/Listener/*'

    secure.listener.request_order:
        class: SecureBundle\Service\Listener\RequestOrderListener
        #arguments: ['@security.token_storage', '@secure.service.order']
        autowire: true
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    SecureBundle\Service\Listener\UserActivityListener:
        class: SecureBundle\Service\Listener\UserActivityListener
        autowire: true
        tags:
            - { name: kernel.event_subscriber }

    #secure.listener.logout:
    #    class: SecureBundle\Service\Listener\LogoutListener
    #    autowire: true
        #arguments: ['@secure.service.user_activity', '@em', '@event_dispatcher']

#    secure.listener.upload_file_gallery:
#        class: SecureBundle\Service\Listener\UploadFileListener
#        arguments: ['@em', '@secure.service.files', '@secure.service.image', '@security.token_storage']
#        tags:
#            - { name: kernel.event_listener, event: oneup_uploader.post_persist.gallery, method: onUpload }
