services:
    _defaults:
        public: true

    SecureBundle\Repository\UserActivityRepository:
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['%user_activity_entity%']

    SecureBundle\Repository\UserOrderRepository:
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['%user_order_entity%']

    SecureBundle\Repository\StatusOrderRepository:
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['%status_order_entity%']

    SecureBundle\Repository\CompanyRepository:
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['%company_entity%']

    SecureBundle\Repository\UserBidRepository:
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['%user_bid_entity%']

    SecureBundle\Repository\SettingRepository:
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['%setting_entity%']

    SecureBundle\Repository\OrderFileRepository:
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['%order_file_entity%']

    SecureBundle\Repository\StageOrderRepository:
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: ['%stage_order_entity%']