#--ManagerController--#

secure_manager_homepage:
    path: secure/manager/homepage
    defaults: { _controller: SecureBundle:Manager:home }

secure_manager_profile:
    path: secure/manager/profile
    defaults: { _controller: SecureBundle:Manager:profile }

#secure_get_order_full_info:
#    path: secure/order/fullInfo/{orderId}
#    defaults: { _controller: SecureBundle:Order:getOrderFullInfo }
#    methods: [GET]
#    requirements:
#        orderId: '\d+'
#    options:
#        expose: true

#--SecureBundle--#

secure_index:
    path: secure/index
    defaults: { _controller: SecureBundle:Secure:index }

secure_download_file:
    path: secure/order/file/download/{type}/{fileId}
    defaults: { _controller: SecureBundle:Secure:downloadFile }
    requirements:
        type: 'attachments|pdf'
        fileId: '\d+'

#--UserController--#

secure_user_homepage:
    path: secure/user/homepage
    defaults: { _controller: SecureBundle:User:home }

secure_user_profile:
    path: secure/user/profile
    defaults: { _controller: SecureBundle:User:profile }

secure_user_orders:
    path: secure/user/orders/{type}
    defaults: { _controller: SecureBundle:User:orders }

secure_user_settings:
    path: secure/user/settings
    defaults: { _controller: SecureBundle:User:settings }

secure_user_order_page:
    path: secure/user/order/{orderId}
    defaults: { _controller: SecureBundle:User:order }
    requirements:
        orderId: '\d+'
    options:
        expose: true

secure_user_bids:
    path: secure/user/bids
    defaults: { _controller: SecureBundle:User:bids }

secure_user_activities:
    path: secure/user/activities
    defaults: { _controller: SecureBundle:User:activities }

#--CompanyController--#

secure_company_info:
    path: secure/company/{companyId}/info
    defaults: { _controller: SecureBundle:Company:info }
    requirements:
        companyId: '\d+'