services:
    _defaults:
        public: true
        bind:
            $em: '@doctrine.orm.entity_manager'
            $packages: '@assets.packages'
            $router: '@router'
            $uploadUserAvatarsDir: '%file_upload_dir_user_avatars%'
            $secureBundleWebDir: '%secure_bundle_web_dir%'
            $repositoryClassMap: '%entity_repositories%'
            $userActivityRepository: '@secure.repository.user_activity'
            $fileService: '@secure.service.file'
            $dateTimeService: '@secure.service.date_time'
            $eventDispatcher: '@event_dispatcher'
            $statusOrderRepository: '@secure.repository.status_order'
            $userOrderRepository: '@secure.repository.user_order'
            $bidService: '@secure.service.bid'
            $settingService: '@secure.service.setting'
            $userBidRepository: '@secure.repository.user_bid'
            $settingRepository: '@secure.repository.setting'

    secure.service.file: '@SecureBundle\Service\FileService'
    secure.service.date_time: '@SecureBundle\Service\DateTimeService'
    secure.service.bid: '@SecureBundle\Service\BidService'
    secure.service.setting: '@SecureBundle\Service\SettingService'

    SecureBundle\Service\:
        resource: '../../../SecureBundle/Service/*'

    SecureBundle\Factory\:
        resource: '../../../SecureBundle/Factory/*'

    secure.twig.extension:
        class: SecureBundle\Twig\SecureTwigExtension
        autowire: true
        public: false
        tags:
            - { name: twig.extension }

#    secure.service.date_time:
#        class: SecureBundle\Service\DateTimeService
#
#    secure.service.orders:
#        class: SecureBundle\Service\OrdersService
#        arguments: ['@em']
#
#    secure.service.repository_factory:
#        class: SecureBundle\Factory\EntityRepositoryFactory
#        arguments: ['%entity_repositories%']
#
#    secure.service.order:
#        class: SecureBundle\Service\UserOrderService
#        arguments:
#            - '@em'
#            - '@router'
#            - '@secure.service.file'
#            - '@secure.service.date_time'
#            - '@secure.repository.status_order'
#            - '@secure.repository.user_order'
#            - '@secure.service.bid'
#            - '@event_dispatcher'
#            - '@secure.service.setting'
#
#    secure.service.file:
#        class: SecureBundle\Service\FileService
#        arguments: ['@em', '@router']
#
#    secure.service.bid:
#        class: SecureBundle\Service\BidService
#        arguments: ['@em', '@secure.service.date_time', '@secure.repository.user_bid']
#
#    secure.service.user:
#        class: SecureBundle\Service\UserService
#        arguments: ['@doctrine.orm.entity_manager', '@assets.packages', '%file_upload_dir_user_avatars%', '%secure_bundle_web_dir%', '@router']
#
#    secure.service.user_activity:
#        class: SecureBundle\Service\UserActivityService
#        arguments: ['@secure.repository.user_activity']
#
#    secure.service.setting:
#        class: SecureBundle\Service\SettingService
#        arguments: ['@secure.repository.setting']
#
#    secure.service.image:
#        class: SecureBundle\Service\ImageService
#        arguments: ['@doctrine.orm.entity_manager', '@router', '@secure.service.user']
#
#    secure.service.status_order:
#        class: SecureBundle\Service\StatusOrderService
#        arguments: ['@secure.repository.status_order']
#
#    secure.service.stage_order:
#        class: SecureBundle\Service\StageOrderService
#        arguments: ['@secure.repository.stage_order']
#
#
#
#    secure.mail_helper:
#        class: SecureBundle\Service\MailService
#        arguments: ['@doctrine.orm.entity_manager', '%mail_options%', '@mailer']

#    auth.captcha_service:
#        class: AuthBundle\Service\Captcha\Captcha

#    secure.validate_file_listener_gallery:
#        class: SecureBundle\EventListener\ValidateFileListener
#        arguments: ['@secure.service.files']
#        tags:
#            - { name: kernel.event_listener, event: oneup_uploader.validation.gallery, method: onValidate }
#
#    secure.file_upload_error_handler:
#        arguments: ['@secure.service.files']
#        class: SecureBundle\Service\Handler\UploadFileErrorHandler