services:
    _defaults:
        public: true
        bind:
            $em: '@doctrine.orm.entity_manager'
            $packages: '@assets.packages'
            $router: '@router'
            $uploadUserAvatarsDir: '%file_upload_dir_user_avatars%'
            $secureBundleWebDir: '%secure_bundle_web_dir%'
            $repositoryClassMap: '%entity_repositories%'
            $userActivityRepository: '@secure.repository.user_activity'
            $fileService: '@secure.service.file'
            $dateTimeService: '@secure.service.date_time'
            $eventDispatcher: '@event_dispatcher'
            $statusOrderRepository: '@secure.repository.status_order'
            $userOrderRepository: '@secure.repository.user_order'
            $userRepository: '@secure.repository.user'
            $bidService: '@secure.service.bid'
            $settingService: '@secure.service.setting'
            $userBidRepository: '@secure.repository.user_bid'
            $settingRepository: '@secure.repository.setting'

    secure.service.file: '@SecureBundle\Service\FileService'
    secure.service.date_time: '@SecureBundle\Service\DateTimeService'
    secure.service.bid: '@SecureBundle\Service\BidService'
    secure.service.setting: '@SecureBundle\Service\SettingService'
    secure.service.user: '@SecureBundle\Service\UserService'

    SecureBundle\Service\:
        resource: '../../../SecureBundle/Service/*'

    SecureBundle\Factory\:
        resource: '../../../SecureBundle/Factory/*'

    secure.twig.extension:
        class: SecureBundle\Twig\SecureTwigExtension
        autowire: true
        public: false
        tags:
            - { name: twig.extension }

#    secure.validate_file_listener_gallery:
#        class: SecureBundle\EventListener\ValidateFileListener
#        arguments: ['@secure.service.files']
#        tags:
#            - { name: kernel.event_listener, event: oneup_uploader.validation.gallery, method: onValidate }
#
#    secure.file_upload_error_handler:
#        arguments: ['@secure.service.files']
#        class: SecureBundle\Service\Handler\UploadFileErrorHandler