services:
    secure.service.date_time:
        class: SecureBundle\Service\DateTimeService

    secure.service.orders:
        class: SecureBundle\Service\OrdersService
        arguments: ['@em']

    secure.service.repository_factory:
        class: SecureBundle\Factory\EntityRepositoryFactory
        arguments: ['%entity_repositories%']

    secure.service.order:
        class: SecureBundle\Service\UserOrderService
        arguments:
            - '@em'
            - '@router'
            - '@secure.service.files'
            - '@secure.service.date_time'
            - '@secure.repository.status_order'
            - '@secure.repository.user_order'

    secure.service.files:
        class: SecureBundle\Service\FileService
        arguments: ['@em', '@router']

    secure.service.bid:
        class: SecureBundle\Service\BidService
        arguments: ['@em', '@secure.service.date_time']

    app.twig:
        class: SecureBundle\Twig\Extension\AppExtension
        tags:
            - { name: twig.extension }

    app.twig_runtime:
        class: SecureBundle\Twig\AppRuntime
        public: false
        tags:
            - { name: twig.runtime }





    secure.image_helper:
        class: SecureBundle\Service\ImageService
        arguments: ['@doctrine.orm.entity_manager', '@router', '@secure.service.user']

    secure.service.user:
        class: SecureBundle\Service\UserService
        arguments: ['@doctrine.orm.entity_manager', '@assets.packages']

    secure.mail_helper:
        class: SecureBundle\Service\MailService
        arguments: ['@doctrine.orm.entity_manager', '%mail_options%', '@mailer']

    secure.upload_file_listener_gallery:
        class: SecureBundle\EventListener\UploadFileListener
        arguments: ['@doctrine.orm.entity_manager', '@secure.service.files', '@secure.image_helper', '@security.token_storage']
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist.gallery, method: onUpload }

    secure.validate_file_listener_gallery:
        class: SecureBundle\EventListener\ValidateFileListener
        arguments: ['@secure.service.files']
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.validation.gallery, method: onValidate }

    secure.file_upload_error_handler:
        arguments: ['@secure.service.files']
        class: SecureBundle\Service\Handler\UploadFileErrorHandler